builds:
  - id: "tdexd-linux"
    main: ./cmd/tdexd
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    binary: tdexd-linux
  - id: "tdexd-darwin"
    main: ./cmd/tdexd
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    binary: tdexd-darwin
  - id: "tdex"
    main: ./cmd/tdex
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    binary: tdex
checksum:
  name_template: "checksums.txt"
signs:
  - artifacts: checksum
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
archives:
  - id: tdexd
    format: binary
    builds:
      - tdexd-linux
      - tdexd-darwin
    name_template: "tdexd-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  - id: tdex
    format: binary
    builds:
      - tdex
    name_template: "tdex-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
#dockers:
#  -
#    goos: linux
#    goarch: amd64
#    goarm: ''
#    binaries:
#    - tdexd-linux
#    - tdex
#    image_templates:
#    - "ghcr.io/tdex-network/tdexd:latest"
#    - "ghcr.io/tdex-network/tdexd:{{ .Tag }}"
#    dockerfile: goreleaser.Dockerfile
#    build_flag_templates:
#    - "--pull"

